version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"   # Host:Container
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=YourServerName;Database=YourDBName;User=YourUserName;Password=YourPassword;TrustServerCertificate=True;"
      RUN_MIGRATIONS: "true"  # Migration Control toggle
      EmailSettings__GmailUser: "YourMailSenderEmail"
      EmailSettings__GmailPass: "YourMailSenderPassword"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourPassword"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge