services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"   # Host:Container
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=EventManagerServer;Database=EventManagerDb;User=sa;Password=YourDbPassword;TrustServerCertificate=True;"
      RUN_MIGRATIONS: "true"  # Add this line for migration control
      EmailSettings__GmailUser: "YourMailSenderEmail"
      EmailSettings__GmailPass: "YourMailSenderPassword"
    depends_on:
      - eventmanagerserver
    networks:
      - app-network

  eventmanagerserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourDbPassword"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge